spring:
  application:
    name: daily-schedule-be

  # Docker? ?? MySQL DB ??
  datasource:
    url: jdbc:mysql://localhost:3307/jaksim_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA (Java Persistence API) ??
  jpa:
    # DBMS?? ??? ??? ??? ???? ??? ???? ?? ??
    # Spring Boot?? ???? MySQL? ???? ???? ??? ?? ????
    # ????? ????? ???? ?? ??
    # database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      # Java Entity ???? ???? DB ???? ???? ????? ??
      # update ?? -> Entity ?? ??? ???? DB ???? ?? (??? ??)
      # create ?? -> ? ?? ??? ?? ???? ??? ?? ?? (??? ??)
      ddl-auto: update
    # JPA? ???? SQL ??? ??? ???? ??
    show-sql: true